const MESSAGES_DATA = [
  {
    title: 'Messages',
    items: [
      {
        id: 1,
        name: 'Leanne Graham',
        email: 'Sincere@april.biz',
        avatar: 'https://robohash.org/1.png',
        priority: 'high',
        message: 'Contact Email not Linked',
        address:
          'Unit 1, Moons Park, Burnt Meadow Road, Moons Moat North Industrial Estate, B98 9PA',
        date: 'May 26, 2022',
        registration: '24.05.2019',
      },
      {
        id: 2,
        name: 'Ervin Howell',
        email: 'Shanna@melissa.tv',
        avatar: 'https://robohash.org/2.png',
        priority: 'low',
        message: 'Adding Images to Featured Posts',
        address: 'South Lodge, Reddish Lane, Lymm,WA13 9PY',
        date: 'May 26, 2022',
        registration: '23.05.2019',
      },
      {
        id: 3,
        name: 'Clementine Bauch',
        email: 'Nathan@yesenia.net',
        avatar: 'https://robohash.org/3.png',
        priority: 'normal',
        message: 'When will I be charged this month?',
        address: '15 Romilly Street, Liverpool,L6 9JL',
        date: 'May 26, 2022',
        registration: '22.05.2019',
      },
      {
        id: 4,
        name: 'Patricia Lebsack',
        email: 'Julianne.OConner@kory.org',
        avatar: 'https://robohash.org/4.png',
        priority: 'high',
        message: 'Payment not going through',
        address: '13 Balfour Crescent, Bracknell, RG12 7JA',
        date: 'May 25, 2022',
        registration: '22.05.2019',
      },
      {
        id: 5,
        name: 'Chelsey Dietrich',
        email: 'Lucio_Hettinger@annie.ca',
        avatar: 'https://robohash.org/5.png',
        priority: 'low',
        message: 'Unable to add replies',
        address: '267 Rundells, Harlow,CM18 7HH',
        date: 'May 25, 2022',
        registration: '21.05.2019',
      },
      {
        id: 6,
        name: 'Mrs. Dennis Schulist',
        email: 'Karley_Dach@jasper.info',
        avatar: 'https://robohash.org/6.png',
        priority: 'normal',
        message: 'Downtime since last week',
        address: '47 Chelmsford Close, Hull,HU9 5DR',
        date: 'May 25, 2022',
        registration: '21.05.2019',
      },
      {
        id: 7,
        name: 'Kurtis Weissnat',
        email: 'Telly.Hoeger@billy.biz',
        avatar: 'https://robohash.org/7.png',
        priority: 'high',
        message: 'Referral Bonus',
        address: '65 Chapel Street, Salford,M3 5BZ',
        date: 'May 24, 2022',
        registration: '20.05.2019',
      },
      {
        id: 8,
        name: 'Nicholas Runolfsdottir V',
        email: 'Sherwood@rosamond.me',
        avatar: 'https://robohash.org/8.png',
        priority: 'low',
        message: 'How do I change my password?',
        address: '16 Cedar Avenue, Poulton-Le-Fylde',
        date: 'May 24, 2022',
        registration: '19.05.2019',
      },
      {
        id: 9,
        name: 'Glenna Reichert',
        email: 'Chaim_McDermott@dana.io',
        avatar: 'https://robohash.org/9.png',
        priority: 'normal',
        message: 'Contact Email not Linked',
        address: 'South Lodge, Reddish Lane, Lymm,WA13 9PY',
        date: 'May 24, 2022',
        registration: '18.05.2019',
      },
      {
        id: 10,
        name: 'Clementina DuBuque',
        email: 'Rey.Padberg@karina.biz',
        avatar: 'https://robohash.org/10.png',
        priority: 'high',
        message: 'Adding Images to Featured Posts',
        address: '15 Romilly Street, Liverpool,L6 9JL',
        date: 'May 23, 2022',
        registration: '17.05.2019',
      },
    ],
  },
];

export default MESSAGES_DATA;
